### PR TITLE
Instead of using the smem output driver of VLC, we now interact direc…

### PR DESCRIPTION
**Pull request by bkocev**
…tly with libvlc via the mediaplayer interface.

### CODE REVIEW

**Comment by planthaber** [comment]
Great, thanks, this lib became incompatible with VLC3.
Can you have a look if it is possible to set the "--network-caching" property through the new way of settings?
The default is one second which is normally too high for our needs.

**Comment by bkocev** [comment]
> Great, thanks, this lib became incompatible with VLC3.
> Can you have a look if it is possible to set the "--network-caching" property through the new way of settings?
> The default is one second which is normally too high for our needs.

"vlc --version" in the vrlab docker returns the following:

VLC media player 3.0.8 Vetinari (revision 3.0.8-0-gf350b6b5a7)
VLC version 3.0.8 Vetinari (3.0.8-0-gf350b6b5a7)
Compiled by buildd on lcy01-amd64-014.buildd (Sep 11 2019 11:39:37)
Compiler: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.

To my understanding, we have VLC3 in the docker container and for me the drivers-video_capture_vlc module//library seems to work. So, I am bit confused by that you say that the lib became incompatible with VLC3. This does not seem to be the case for me. Maybe, something else is the problem.

**Review by Tbonrez808 — APPROVED** [review]

**Comment by planthaber** [comment]
What I meant was that the old version in the repo became incompatible with vlc3 as documentation why we made these changes.

**Comment by bkocev** [comment]
Regarding the  "--network-caching" property, I found something along these lines:

_mp = new MediaPlayer(_libVLC);
videoView1.MediaPlayer = _mp;//not necessary
_media = new Media(_libVLC, "rtp://@:12016", FromType.FromLocation);
_media.AddOption(":network-caching=1000");

See https://forum.videolan.org/viewtopic.php?f=32&t=153754&p=504504&hilit=network+caching&sid=9f61d0d42fcc255f45f8ceba4b257dea#p504504.

However, I think that the above code is compatible with the C# version of this interface, i.e., in C++ I am not able to compile the above code.

I am still investigating if there is an alternative or if I am doing something wrong.

**Comment by bkocev** [comment]
This successfully compiled:

libvlc_media_add_option(vlcm, ":network-caching=1000");

@planthaber: What would you recommend to set it with by default?

**Comment by planthaber** [comment]
> libvlc_media_add_option(vlcm, ":network-caching=1000"); 
> @planthaber: What would you recommend to set it with by default?

1000 is the default when nothing is set, so setting it all the time won't hurt.
I think it should stay a optional paramater in the constructor, but leave the default of 1000 untouched

https://github.com/rock-drivers/drivers-video_capture_vlc/blob/master/src/VlcCapture.h#L48

```VlcCapture(std::string url = "", int input_buffer_ms = 1000);```

**Comment by bkocev** [comment]
@planthaber: Now, we provide means for setting the parameter network-caching. I pushed these changes to the branch smemElimination, i.e., I believe you may now merge the pull request. Thanks.

**Pull request merged**
